BEGIN;

DROP TABLE IF EXISTS AMDCSS; 
DROP TABLE IF EXISTS ARCHIVE; 
DROP TABLE IF EXISTS AWARD; 
DROP TABLE IF EXISTS COMBINE; 
DROP TABLE IF EXISTS FAIROPP; 
DROP TABLE IF EXISTS FSTD;
DROP TABLE IF EXISTS JA; 
DROP TABLE IF EXISTS MOD; 
DROP TABLE IF EXISTS PRESOL; 
DROP TABLE IF EXISTS SNOTE; 
DROP TABLE IF EXISTS SRCSGT; 
DROP TABLE IF EXISTS UNARCHIVE; 
DROP TABLE IF EXISTS ITB;
DROP TABLE IF EXISTS SSALE;

CREATE TABLE PRESOL(
	FBO_AGENCY TEXT,
	FBO_ARCHDATE TEXT,
	FBO_AWARDEE TEXT,
	FBO_AWDAMT TEXT,
	FBO_AWDDATE TEXT,
	FBO_AWDNBR TEXT,
	FBO_CLASSCOD TEXT,
	FBO_CONTACT TEXT,
	FBO_CORRECTION TEXT,
	FBO_DATE TEXT,
	FBO_DESC TEXT,
	FBO_DONBR TEXT,
	FBO_EMAIL TEXT,
	FBO_FOJA TEXT,
	FBO_LINENBR TEXT,
	FBO_LINK TEXT,
	FBO_LOCATION TEXT,
	FBO_MODNBR TEXT,
	FBO_NAICS TEXT,
	FBO_NTYPE TEXT,
	FBO_OFFADD TEXT,
	FBO_OFFICE TEXT,
	FBO_PASSWORD TEXT,
	FBO_POPADDRESS TEXT,
	FBO_POPCOUNTRY TEXT,
	FBO_POPZIP TEXT,
	FBO_RESPDATE TEXT,
	FBO_SETASIDE TEXT,
	FBO_SOLNBR TEXT,
	FBO_STAUTH TEXT,
	FBO_SUBJECT TEXT,
	FBO_URL TEXT,
	FBO_YEAR TEXT,
	FBO_ZIP TEXT,
	FBO_POC_EMAIL TEXT,
	FBO_POC_EMAIL_DESC TEXT,
	FBO_LINK_URL TEXT,
	FBO_LINK_DESC TEXT,
	FBO_FILENAME TEXT,
	FBO_RECORD_TEXT TEXT
 );



CREATE TABLE AMDCSS		AS SELECT * FROM PRESOL WHERE 1=2;
CREATE TABLE ARCHIVE	AS SELECT * FROM PRESOL WHERE 1=2;
CREATE TABLE AWARD		AS SELECT * FROM PRESOL WHERE 1=2;
CREATE TABLE COMBINE	AS SELECT * FROM PRESOL WHERE 1=2;
CREATE TABLE FAIROPP	AS SELECT * FROM PRESOL WHERE 1=2;
CREATE TABLE JA			AS SELECT * FROM PRESOL WHERE 1=2;
CREATE TABLE MOD		AS SELECT * FROM PRESOL WHERE 1=2;
CREATE TABLE SNOTE		AS SELECT * FROM PRESOL WHERE 1=2;
CREATE TABLE SRCSGT		AS SELECT * FROM PRESOL WHERE 1=2;
CREATE TABLE UNARCHIVE	AS SELECT * FROM PRESOL WHERE 1=2;
CREATE TABLE FSTD		AS SELECT * FROM PRESOL WHERE 1=2;
CREATE TABLE SSALE		AS SELECT * FROM PRESOL WHERE 1=2;
CREATE TABLE ITB		AS SELECT * FROM PRESOL WHERE 1=2;

COPY AMDCSS FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_AMDCSS.csv' WITH CSV; 
COPY ARCHIVE FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_ARCHIVE.csv' WITH CSV; 
COPY AWARD FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_AWARD.csv' WITH CSV; 
COPY COMBINE FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_COMBINE.csv' WITH CSV; 
COPY FAIROPP FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_FAIROPP.csv' WITH CSV; 
COPY JA FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_JA.csv' WITH CSV; 
COPY MOD FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_MOD.csv' WITH CSV; 
COPY PRESOL FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_PRESOL.csv' WITH CSV; 
COPY SNOTE FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_SNOTE.csv' WITH CSV; 
COPY SRCSGT FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_SRCSGT.csv' WITH CSV; 
COPY UNARCHIVE FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_UNARCHIVE.csv' WITH CSV; 
COPY FSTD FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_FSTD.csv' WITH CSV; 
COPY SSALE FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_SSALE.csv' WITH CSV; 
COPY ITB FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_ITB.csv' WITH CSV; 



/*
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_AGENCY));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_ARCHDATE));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_AWARDEE));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_AWDAMT));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_AWDDATE));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_AWDNBR));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_CLASSCOD));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_CONTACT));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_DATE));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_DESC));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_DONBR));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_PCO_EMAIL));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_FOJA));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_LINENBR));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_LINK));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_LOCATION));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_MODNBR));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_NAICS));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_NTYPE));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_OFFADD));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_OFFICE));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_POPADDRESS));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_POPCOUNTRY));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_POPZIP));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_RESPDATE));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_SETASIDE));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_SOLNBR));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_STAUTH));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_SUBJECT));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_URL));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_YEAR));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_ZIP));
CREATE INDEX ON PRESOL USING GIN (to_tsvector('english', FBO_FILENAME));

CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_AGENCY));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_ARCHDATE));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_AWARDEE));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_AWDAMT));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_AWDDATE));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_AWDNBR));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_CLASSCOD));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_CONTACT));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_DATE));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_DESC));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_DONBR));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_EMAIL));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_FOJA));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_LINENBR));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_LINK));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_LOCATION));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_MODNBR));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_NAICS));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_NTYPE));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_OFFADD));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_OFFICE));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_POPADDRESS));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_POPCOUNTRY));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_POPZIP));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_RESPDATE));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_SETASIDE));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_SOLNBR));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_STAUTH));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_SUBJECT));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_URL));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_YEAR));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_ZIP));
CREATE INDEX ON COMBINE USING GIN (to_tsvector('english', FBO_FILENAME));
*/
COMMIT;
