BEGIN;

DROP TABLE IF EXISTS AMDCSS_CSV; 
DROP TABLE IF EXISTS ARCHIVE_CSV; 
DROP TABLE IF EXISTS AWARD_CSV; 
DROP TABLE IF EXISTS COMBINE_CSV; 
DROP TABLE IF EXISTS EMAIL_CSV; 
DROP TABLE IF EXISTS FAIROPP_CSV; 
DROP TABLE IF EXISTS JA_CSV; 
DROP TABLE IF EXISTS MOD_CSV; 
DROP TABLE IF EXISTS PRESOL_CSV; 
DROP TABLE IF EXISTS SNOTE_CSV; 
DROP TABLE IF EXISTS SRCSGT_CSV; 
DROP TABLE IF EXISTS UNARCHIVE_CSV; 
DROP TABLE IF EXISTS COMBINED_CSV;
DROP TABLE IF EXISTS FBO_AGENCY;
DROP TABLE IF EXISTS FBO_ARCHDATE;
DROP TABLE IF EXISTS FBO_AWARDEE;
DROP TABLE IF EXISTS FBO_AWDAMT;
DROP TABLE IF EXISTS FBO_AWDDATE;
DROP TABLE IF EXISTS FBO_AWDNBR;
DROP TABLE IF EXISTS FBO_CLASSCOD;
DROP TABLE IF EXISTS FBO_CONTACT;
DROP TABLE IF EXISTS FBO_DATE;
DROP TABLE IF EXISTS FBO_DESC;
DROP TABLE IF EXISTS FBO_DONBR;
DROP TABLE IF EXISTS FBO_EMAIL;
DROP TABLE IF EXISTS FBO_FOJA;
DROP TABLE IF EXISTS FBO_LINENBR;
DROP TABLE IF EXISTS FBO_LINK;
DROP TABLE IF EXISTS FBO_LOCATION;
DROP TABLE IF EXISTS FBO_MODNBR;
DROP TABLE IF EXISTS FBO_NAICS;
DROP TABLE IF EXISTS FBO_NTYPE;
DROP TABLE IF EXISTS FBO_OFFADD;
DROP TABLE IF EXISTS FBO_OFFICE;
DROP TABLE IF EXISTS FBO_POPADDRESS;
DROP TABLE IF EXISTS FBO_POPCOUNTRY;
DROP TABLE IF EXISTS FBO_POPZIP;
DROP TABLE IF EXISTS FBO_RESPDATE;
DROP TABLE IF EXISTS FBO_SETASIDE;
DROP TABLE IF EXISTS FBO_SOLNBR;
DROP TABLE IF EXISTS FBO_STAUTH;
DROP TABLE IF EXISTS FBO_SUBJECT;
DROP TABLE IF EXISTS FBO_URL;
DROP TABLE IF EXISTS FBO_YEAR;
DROP TABLE IF EXISTS FBO_ZIP;
DROP TABLE IF EXISTS FBO_FILENAME;

CREATE TABLE PRESOL_CSV(
	FBO_AGENCY TEXT,
	FBO_ARCHDATE TEXT,
	FBO_AWARDEE TEXT,
	FBO_AWDAMT TEXT,
	FBO_AWDDATE TEXT,
	FBO_AWDNBR TEXT,
	FBO_CLASSCOD TEXT,
	FBO_CONTACT TEXT,
	FBO_DATE TEXT,
	FBO_DESC TEXT,
	FBO_DONBR TEXT,
	FBO_EMAIL TEXT,
	FBO_FOJA TEXT,
	FBO_LINENBR TEXT,
	FBO_LINK TEXT,
	FBO_LOCATION TEXT,
	FBO_MODNBR TEXT,
	FBO_NAICS TEXT,
	FBO_NTYPE TEXT,
	FBO_OFFADD TEXT,
	FBO_OFFICE TEXT,
	FBO_POPADDRESS TEXT,
	FBO_POPCOUNTRY TEXT,
	FBO_POPZIP TEXT,
	FBO_RESPDATE TEXT,
	FBO_SETASIDE TEXT,
	FBO_SOLNBR TEXT,
	FBO_STAUTH TEXT,
	FBO_SUBJECT TEXT,
	FBO_URL TEXT,
	FBO_YEAR TEXT,
	FBO_ZIP TEXT,
	FBO_FILENAME TEXT
);

SELECT * INTO AMDCSS_CSV FROM PRESOL_CSV WHERE 1=2;
SELECT * INTO ARCHIVE_CSV FROM PRESOL_CSV WHERE 1=2;
SELECT * INTO AWARD_CSV FROM PRESOL_CSV WHERE 1=2;
SELECT * INTO COMBINE_CSV FROM PRESOL_CSV WHERE 1=2;
SELECT * INTO EMAIL_CSV FROM PRESOL_CSV WHERE 1=2;
SELECT * INTO FAIROPP_CSV FROM PRESOL_CSV WHERE 1=2;
SELECT * INTO JA_CSV FROM PRESOL_CSV WHERE 1=2;
SELECT * INTO MOD_CSV FROM PRESOL_CSV WHERE 1=2;
SELECT * INTO SNOTE_CSV FROM PRESOL_CSV WHERE 1=2;
SELECT * INTO SRCSGT_CSV FROM PRESOL_CSV WHERE 1=2;
SELECT * INTO UNARCHIVE_CSV FROM PRESOL_CSV WHERE 1=2;
SELECT * INTO COMBINED_CSV FROM PRESOL_CSV WHERE 1=2;


COPY AMDCSS_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_AMDCSS.csv' WITH CSV; 
COPY ARCHIVE_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_ARCHIVE.csv' WITH CSV; 
COPY AWARD_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_AWARD.csv' WITH CSV; 
COPY COMBINE_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_COMBINE.csv' WITH CSV; 
COPY EMAIL_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_EMAIL.csv' WITH CSV; 
COPY FAIROPP_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_FAIROPP.csv' WITH CSV; 
COPY JA_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_JA.csv' WITH CSV; 
COPY MOD_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_MOD.csv' WITH CSV; 
COPY PRESOL_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_PRESOL.csv' WITH CSV; 
COPY SNOTE_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_SNOTE.csv' WITH CSV; 
COPY SRCSGT_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_SRCSGT.csv' WITH CSV; 
COPY UNARCHIVE_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_UNARCHIVE.csv' WITH CSV; 

COPY COMBINED_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_AMDCSS.csv' WITH CSV; 
COPY COMBINED_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_ARCHIVE.csv' WITH CSV; 
COPY COMBINED_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_AWARD.csv' WITH CSV; 
COPY COMBINED_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_COMBINE.csv' WITH CSV; 
COPY COMBINED_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_EMAIL.csv' WITH CSV; 
COPY COMBINED_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_FAIROPP.csv' WITH CSV; 
COPY COMBINED_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_JA.csv' WITH CSV; 
COPY COMBINED_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_MOD.csv' WITH CSV; 
COPY COMBINED_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_PRESOL.csv' WITH CSV; 
COPY COMBINED_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_SNOTE.csv' WITH CSV; 
COPY COMBINED_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_SRCSGT.csv' WITH CSV; 
COPY COMBINED_CSV FROM '/Users/stephen/Development/fboparser.git/csv/fbofeed_UNARCHIVE.csv' WITH CSV; 


CREATE TABLE FBO_AGENCY (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_ARCHDATE (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_AWARDEE (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_AWDAMT (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_AWDDATE (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_AWDNBR (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_CLASSCOD (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_CONTACT (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_DATE (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_DESC (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_DONBR (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_EMAIL (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_FOJA (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_LINENBR (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_LINK (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_LOCATION (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_MODNBR (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_NAICS (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_NTYPE (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_OFFADD (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_OFFICE (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_POPADDRESS (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_POPCOUNTRY (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_POPZIP (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_RESPDATE (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_SETASIDE (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_SOLNBR (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_STAUTH (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_SUBJECT (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_URL (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_YEAR (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_ZIP (
	ID SERIAL,
	NAME TEXT
);

CREATE TABLE FBO_FILENAME (
	ID SERIAL,
	NAME TEXT
);

CREATE INDEX ON FBO_AGENCY USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_ARCHDATE USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_AWARDEE USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_AWDAMT USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_AWDDATE USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_AWDNBR USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_CLASSCOD USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_CONTACT USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_DATE USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_DESC USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_DONBR USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_EMAIL USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_FOJA USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_LINENBR USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_LINK USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_LOCATION USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_MODNBR USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_NAICS USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_NTYPE USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_OFFADD USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_OFFICE USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_POPADDRESS USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_POPCOUNTRY USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_POPZIP USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_RESPDATE USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_SETASIDE USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_SOLNBR USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_STAUTH USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_SUBJECT USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_URL USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_YEAR USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_ZIP USING GIN (to_tsvector('english', name));
CREATE INDEX ON FBO_FILENAME USING GIN (to_tsvector('english', name));

INSERT INTO FBO_AGENCY (NAME) SELECT DISTINCT FBO_AGENCY FROM COMBINED_CSV WHERE FBO_AGENCY IS NOT NULL;
INSERT INTO FBO_ARCHDATE (NAME) SELECT DISTINCT FBO_ARCHDATE FROM COMBINED_CSV WHERE FBO_ARCHDATE IS NOT NULL;
INSERT INTO FBO_AWARDEE (NAME) SELECT DISTINCT FBO_AWARDEE FROM COMBINED_CSV WHERE FBO_AWARDEE IS NOT NULL;
INSERT INTO FBO_AWDAMT (NAME) SELECT DISTINCT FBO_AWDAMT FROM COMBINED_CSV WHERE FBO_AWDAMT IS NOT NULL;
INSERT INTO FBO_AWDDATE (NAME) SELECT DISTINCT FBO_AWDDATE FROM COMBINED_CSV WHERE FBO_AWDDATE IS NOT NULL;
INSERT INTO FBO_AWDNBR (NAME) SELECT DISTINCT FBO_AWDNBR FROM COMBINED_CSV WHERE FBO_AWDNBR IS NOT NULL;
INSERT INTO FBO_CLASSCOD (NAME) SELECT DISTINCT FBO_CLASSCOD FROM COMBINED_CSV WHERE FBO_CLASSCOD IS NOT NULL;
INSERT INTO FBO_CONTACT (NAME) SELECT DISTINCT FBO_CONTACT FROM COMBINED_CSV WHERE FBO_CONTACT IS NOT NULL;
INSERT INTO FBO_DATE (NAME) SELECT DISTINCT FBO_DATE FROM COMBINED_CSV WHERE FBO_DATE IS NOT NULL;
INSERT INTO FBO_DESC (NAME) SELECT DISTINCT FBO_DESC FROM COMBINED_CSV WHERE FBO_DESC IS NOT NULL;
INSERT INTO FBO_DONBR (NAME) SELECT DISTINCT FBO_DONBR FROM COMBINED_CSV WHERE FBO_DONBR IS NOT NULL;
INSERT INTO FBO_EMAIL (NAME) SELECT DISTINCT FBO_EMAIL FROM COMBINED_CSV WHERE FBO_EMAIL IS NOT NULL;
INSERT INTO FBO_FOJA (NAME) SELECT DISTINCT FBO_FOJA FROM COMBINED_CSV WHERE FBO_FOJA IS NOT NULL;
INSERT INTO FBO_LINENBR (NAME) SELECT DISTINCT FBO_LINENBR FROM COMBINED_CSV WHERE FBO_LINENBR IS NOT NULL;
INSERT INTO FBO_LINK (NAME) SELECT DISTINCT FBO_LINK FROM COMBINED_CSV WHERE FBO_LINK IS NOT NULL;
INSERT INTO FBO_LOCATION (NAME) SELECT DISTINCT FBO_LOCATION FROM COMBINED_CSV WHERE FBO_LOCATION IS NOT NULL;
INSERT INTO FBO_MODNBR (NAME) SELECT DISTINCT FBO_MODNBR FROM COMBINED_CSV WHERE FBO_MODNBR IS NOT NULL;
INSERT INTO FBO_NAICS (NAME) SELECT DISTINCT FBO_NAICS FROM COMBINED_CSV WHERE FBO_NAICS IS NOT NULL;
INSERT INTO FBO_NTYPE (NAME) SELECT DISTINCT FBO_NTYPE FROM COMBINED_CSV WHERE FBO_NTYPE IS NOT NULL;
INSERT INTO FBO_OFFADD (NAME) SELECT DISTINCT FBO_OFFADD FROM COMBINED_CSV WHERE FBO_OFFADD IS NOT NULL;
INSERT INTO FBO_OFFICE (NAME) SELECT DISTINCT FBO_OFFICE FROM COMBINED_CSV WHERE FBO_OFFICE IS NOT NULL;
INSERT INTO FBO_POPADDRESS (NAME) SELECT DISTINCT FBO_POPADDRESS FROM COMBINED_CSV WHERE FBO_POPADDRESS IS NOT NULL;
INSERT INTO FBO_POPCOUNTRY (NAME) SELECT DISTINCT FBO_POPCOUNTRY FROM COMBINED_CSV WHERE FBO_POPCOUNTRY IS NOT NULL;
INSERT INTO FBO_POPZIP (NAME) SELECT DISTINCT FBO_POPZIP FROM COMBINED_CSV WHERE FBO_POPZIP IS NOT NULL;
INSERT INTO FBO_RESPDATE (NAME) SELECT DISTINCT FBO_RESPDATE FROM COMBINED_CSV WHERE FBO_RESPDATE IS NOT NULL;
INSERT INTO FBO_SETASIDE (NAME) SELECT DISTINCT FBO_SETASIDE FROM COMBINED_CSV WHERE FBO_SETASIDE IS NOT NULL;
INSERT INTO FBO_SOLNBR (NAME) SELECT DISTINCT FBO_SOLNBR FROM COMBINED_CSV WHERE FBO_SOLNBR IS NOT NULL;
INSERT INTO FBO_STAUTH (NAME) SELECT DISTINCT FBO_STAUTH FROM COMBINED_CSV WHERE FBO_STAUTH IS NOT NULL;
INSERT INTO FBO_SUBJECT (NAME) SELECT DISTINCT FBO_SUBJECT FROM COMBINED_CSV WHERE FBO_SUBJECT IS NOT NULL;
INSERT INTO FBO_URL (NAME) SELECT DISTINCT FBO_URL FROM COMBINED_CSV WHERE FBO_URL IS NOT NULL;
INSERT INTO FBO_YEAR (NAME) SELECT DISTINCT FBO_YEAR FROM COMBINED_CSV WHERE FBO_YEAR IS NOT NULL;
INSERT INTO FBO_ZIP (NAME) SELECT DISTINCT FBO_ZIP FROM COMBINED_CSV WHERE FBO_ZIP IS NOT NULL;
INSERT INTO FBO_FILENAME (NAME) SELECT DISTINCT FBO_FILENAME FROM COMBINED_CSV WHERE FBO_FILENAME IS NOT NULL;

COMMIT;
