BEGIN;

\set PWD '\'' `echo $PWD`
\set CSVDIR :PWD '/generic/csv'

\set SETASIDE_TYPES_FILENAME :CSVDIR '/setaside_types.csv\''
\set PRODUCT_CODES_FILENAME :CSVDIR '/product_codes.csv\''
\set SERVICE_CODES_FILENAME :CSVDIR '/service_codes.csv\''
\set NAICS_CODES_FILENAME :CSVDIR '/naics.csv\''
\set JA_STAT_AUTH_FILENAME :CSVDIR '/ja_stat_auth.csv\''
\set FAIROPPS_JUST_AUTH_FILENAME :CSVDIR '/fairopp_just_auth.csv\''

DROP TABLE IF EXISTS SETASIDE_TYPES;
DROP TABLE IF EXISTS PRODUCT_CODES;
DROP TABLE IF EXISTS SERVICE_CODES;
DROP TABLE IF EXISTS NAICS_CODES;
DROP TABLE IF EXISTS FAIROPPS_JUST_AUTH;
DROP TABLE IF EXISTS JA_STAT_AUTH;

CREATE TABLE SETASIDE_TYPES (
	TYPE TEXT,
	FAR_REFERENCE TEXT
);

CREATE TABLE PRODUCT_CODES (
	CODE TEXT,
	DESCRIPTION TEXT
);

CREATE TABLE SERVICE_CODES (
	CODE TEXT,
	DESCRIPTION TEXT
);

CREATE TABLE NAICS_CODES (
	CODE TEXT,
	DESCRIPTION TEXT
);

CREATE TABLE JA_STAT_AUTH (
	DESCRIPTION TEXT
);

CREATE TABLE FAIROPPS_JUST_AUTH (
	DESCRIPTION TEXT
);

COPY SETASIDE_TYPES FROM :SETASIDE_TYPES_FILENAME WITH CSV;
COPY PRODUCT_CODES FROM :PRODUCT_CODES_FILENAME WITH CSV;
COPY SERVICE_CODES FROM :SERVICE_CODES_FILENAME WITH CSV;
COPY NAICS_CODES FROM :NAICS_CODES_FILENAME WITH CSV;
COPY FAIROPPS_JUST_AUTH FROM :FAIROPPS_JUST_AUTH_FILENAME WITH CSV;
COPY JA_STAT_AUTH FROM :JA_STAT_AUTH_FILENAME WITH CSV;

CREATE INDEX ON SETASIDE_TYPES (TYPE, FAR_REFERENCE);
CREATE INDEX ON PRODUCT_CODES (CODE, DESCRIPTION);
CREATE INDEX ON SERVICE_CODES (CODE, DESCRIPTION);
CREATE INDEX ON NAICS_CODES (CODE, DESCRIPTION);
CREATE INDEX ON JA_STAT_AUTH (DESCRIPTION);
CREATE INDEX ON FAIROPPS_JUST_AUTH (DESCRIPTION);

COMMIT;