BEGIN;
UPDATE NOTICES SET FBO_AWDDATE=to_date(FBO_AWDDATE, 'YYYY-MM-DD') WHERE FBO_AWDDATE ~ '00:00:00';
UPDATE NOTICES SET FBO_AWDDATE=to_date(FBO_AWDDATE, 'MMDDYY') WHERE FBO_AWDDATE ~ '[0-9]{6}';
UPDATE NOTICES SET FBO_DATE=to_date(FBO_DATE||FBO_YEAR, 'MMDDYY') WHERE FBO_DATE IS NOT NULL AND FBO_YEAR IS NOT NULL;
UPDATE NOTICES SET FBO_RESPDATE=to_date(FBO_RESPDATE, 'MMDDYY') WHERE FBO_RESPDATE IS NOT NULL;
UPDATE NOTICES SET FBO_ARCHDATE=to_date(FBO_ARCHDATE, 'MMDDYYYY') WHERE FBO_ARCHDATE IS NOT NULL;

CREATE TABLE FBO_AGENCY (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_ARCHDATE (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE DATE UNIQUE
);

CREATE TABLE FBO_AWARDEE (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_AWDAMT (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_AWDDATE (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE DATE UNIQUE
);

CREATE TABLE FBO_AWDNBR (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_CBAC (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_CLASSCOD (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_CONTACT (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_CORRECTION (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_DATE (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE DATE UNIQUE
);

CREATE TABLE FBO_DESC (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_DONBR (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_EMAIL (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_FOJA (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_LINENBR (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_LINK (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_LOCATION (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_MODNBR (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_NAICS (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_NTYPE (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_OFFADD (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_OFFICE (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_PASSWORD (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_POPADDRESS (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_POPCOUNTRY (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_POPZIP (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_RESPDATE (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE DATE UNIQUE
);

CREATE TABLE FBO_SETASIDE (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_SOLNBR (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_STAUTH (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_SUBJECT (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_URL (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_ZIP (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_POC_EMAIL (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_POC_EMAIL_DESC (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_LINK_URL (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

CREATE TABLE FBO_LINK_DESC (
	KEY BIGSERIAL PRIMARY KEY,
	VALUE TEXT UNIQUE
);

INSERT INTO FBO_ARCHDATE(VALUE) SELECT DISTINCT FBO_ARCHDATE FROM NOTICES;
INSERT INTO FBO_AWDDATE(VALUE) SELECT DISTINCT FBO_AWDDATE FROM NOTICES;
INSERT INTO FBO_DATE(VALUE) SELECT DISTINCT FBO_DATE FROM NOTICES;
INSERT INTO FBO_RESPDATE(VALUE) SELECT DISTINCT FBO_RESPDATE FROM NOTICES;


INSERT INTO FBO_AGENCY(VALUE) SELECT DISTINCT FBO_AGENCY FROM NOTICES;
INSERT INTO FBO_AWARDEE(VALUE) SELECT DISTINCT FBO_AWARDEE FROM NOTICES;
INSERT INTO FBO_AWDAMT(VALUE) SELECT DISTINCT FBO_AWDAMT FROM NOTICES;
INSERT INTO FBO_AWDNBR(VALUE) SELECT DISTINCT FBO_AWDNBR FROM NOTICES;
INSERT INTO FBO_CBAC(VALUE) SELECT DISTINCT FBO_CBAC FROM NOTICES;
INSERT INTO FBO_CLASSCOD(VALUE) SELECT DISTINCT FBO_CLASSCOD FROM NOTICES;
INSERT INTO FBO_CONTACT(VALUE) SELECT DISTINCT FBO_CONTACT FROM NOTICES;
INSERT INTO FBO_CORRECTION(VALUE) SELECT DISTINCT FBO_CORRECTION FROM NOTICES;
INSERT INTO FBO_DESC(VALUE) SELECT DISTINCT FBO_DESC FROM NOTICES;
INSERT INTO FBO_DONBR(VALUE) SELECT DISTINCT FBO_DONBR FROM NOTICES;
INSERT INTO FBO_EMAIL(VALUE) SELECT DISTINCT FBO_EMAIL FROM NOTICES;
INSERT INTO FBO_FOJA(VALUE) SELECT DISTINCT FBO_FOJA FROM NOTICES;
INSERT INTO FBO_LINENBR(VALUE) SELECT DISTINCT FBO_LINENBR FROM NOTICES;
INSERT INTO FBO_LINK(VALUE) SELECT DISTINCT FBO_LINK FROM NOTICES;
INSERT INTO FBO_LOCATION(VALUE) SELECT DISTINCT FBO_LOCATION FROM NOTICES;
INSERT INTO FBO_MODNBR(VALUE) SELECT DISTINCT FBO_MODNBR FROM NOTICES;
INSERT INTO FBO_NAICS(VALUE) SELECT DISTINCT FBO_NAICS FROM NOTICES;
INSERT INTO FBO_NTYPE(VALUE) SELECT DISTINCT FBO_NTYPE FROM NOTICES;
INSERT INTO FBO_OFFADD(VALUE) SELECT DISTINCT FBO_OFFADD FROM NOTICES;
INSERT INTO FBO_OFFICE(VALUE) SELECT DISTINCT FBO_OFFICE FROM NOTICES;
INSERT INTO FBO_PASSWORD(VALUE) SELECT DISTINCT FBO_PASSWORD FROM NOTICES;
INSERT INTO FBO_POPADDRESS(VALUE) SELECT DISTINCT FBO_POPADDRESS FROM NOTICES;
INSERT INTO FBO_POPCOUNTRY(VALUE) SELECT DISTINCT FBO_POPCOUNTRY FROM NOTICES;
INSERT INTO FBO_POPZIP(VALUE) SELECT DISTINCT FBO_POPZIP FROM NOTICES;
INSERT INTO FBO_SETASIDE(VALUE) SELECT DISTINCT FBO_SETASIDE FROM NOTICES;
INSERT INTO FBO_SOLNBR(VALUE) SELECT DISTINCT FBO_SOLNBR FROM NOTICES;
INSERT INTO FBO_STAUTH(VALUE) SELECT DISTINCT FBO_STAUTH FROM NOTICES;
INSERT INTO FBO_SUBJECT(VALUE) SELECT DISTINCT FBO_SUBJECT FROM NOTICES;
INSERT INTO FBO_URL(VALUE) SELECT DISTINCT FBO_URL FROM NOTICES;
INSERT INTO FBO_ZIP(VALUE) SELECT DISTINCT FBO_ZIP FROM NOTICES;
INSERT INTO FBO_POC_EMAIL(VALUE) SELECT DISTINCT FBO_POC_EMAIL FROM NOTICES;
INSERT INTO FBO_POC_EMAIL_DESC(VALUE) SELECT DISTINCT FBO_POC_EMAIL_DESC FROM NOTICES;
INSERT INTO FBO_LINK_URL(VALUE) SELECT DISTINCT FBO_LINK_URL FROM NOTICES;
INSERT INTO FBO_LINK_DESC(VALUE) SELECT DISTINCT FBO_LINK_DESC FROM NOTICES;

COMMIT;