BEGIN;

\set PWD '\'' `echo $PWD`

CREATE INDEX ON NOTICES(ARCHDATE);
CREATE INDEX ON NOTICES(AWDDATE);
CREATE INDEX ON NOTICES(NOTICE_DATE);
CREATE INDEX ON NOTICES(RESPDATE);
CREATE INDEX ON NOTICES(notice_type);
CREATE INDEX ON NOTICES(agency);
CREATE INDEX ON NOTICES(awardee);
CREATE INDEX ON NOTICES(awdamt);
CREATE INDEX ON NOTICES(awdnbr);
CREATE INDEX ON NOTICES(cbac);
CREATE INDEX ON NOTICES(classcod);
CREATE INDEX ON NOTICES(contact);
CREATE INDEX ON NOTICES(correction);
CREATE INDEX ON NOTICES(notice_desc);
CREATE INDEX ON NOTICES(donbr);
CREATE INDEX ON NOTICES(foja);
CREATE INDEX ON NOTICES(linenbr);
CREATE INDEX ON NOTICES(location);
CREATE INDEX ON NOTICES(modnbr);
CREATE INDEX ON NOTICES(naics);
CREATE INDEX ON NOTICES(ntype);
CREATE INDEX ON NOTICES(offadd);
CREATE INDEX ON NOTICES(office);
CREATE INDEX ON NOTICES(password);
CREATE INDEX ON NOTICES(popaddress);
CREATE INDEX ON NOTICES(popcountry);
CREATE INDEX ON NOTICES(popzip);
CREATE INDEX ON NOTICES(setaside);
CREATE INDEX ON NOTICES(solnbr);
CREATE INDEX ON NOTICES(stauth);
CREATE INDEX ON NOTICES(subject);
CREATE INDEX ON NOTICES(old_year);
CREATE INDEX ON NOTICES(url);
CREATE INDEX ON NOTICES(zip);
CREATE INDEX ON NOTICES(poc_email);
CREATE INDEX ON NOTICES(poc_email_desc);
CREATE INDEX ON NOTICES(link_url);
CREATE INDEX ON NOTICES(link_desc);

COMMIT;
