BEGIN;

\set CSVDIR '\'/Users/stephen/Development/fboparser.git/db_data/csv'
\set SETASIDE_TYPES_FILENAME :CSVDIR '/setaside_types.csv\''
\set PRODUCT_CODES_FILENAME :CSVDIR '/product_codes.csv\''
\set SERVICE_CODES_FILENAME :CSVDIR '/service_codes.csv\''

DROP TABLE IF EXISTS SETASIDE_TYPES;
DROP TABLE IF EXISTS PRODUCT_CODES;
DROP TABLE IF EXISTS SERVICE_CODES;
DROP TABLE IF EXISTS NAICS_CODES;

CREATE TABLE SETASIDE_TYPES (
	TYPE TEXT,
	FAR_REFERENCE TEXT
);

CREATE TABLE PRODUCT_CODES (
	CODE TEXT,
	DESCRIPTION TEXT
);

CREATE TABLE SERVICE_CODES (
	CODE TEXT,
	DESCRIPTION TEXT
);

CREATE TABLE NAICS_CODES (
	CODE TEXT,
	DESCRIPTION TEXT
);

COPY SETASIDE_TYPES FROM :SETASIDE_TYPES_FILENAME WITH CSV;
COPY PRODUCT_CODES FROM :PRODUCT_CODES_FILENAME WITH CSV;
COPY SERVICE_CODES FROM :SERVICE_CODES_FILENAME WITH CSV;

COMMIT;