BEGIN;
DROP TABLE IF EXISTS FBO_ARCHDATE;
DROP TABLE IF EXISTS FBO_AWARDEE;
DROP TABLE IF EXISTS FBO_AWDAMT;
DROP TABLE IF EXISTS FBO_AWDDATE;
DROP TABLE IF EXISTS FBO_AWDNBR;
DROP TABLE IF EXISTS FBO_CBAC;
DROP TABLE IF EXISTS FBO_CLASSCOD;
DROP TABLE IF EXISTS FBO_CONTACT;
DROP TABLE IF EXISTS FBO_CORRECTION;
DROP TABLE IF EXISTS FBO_DATE;
DROP TABLE IF EXISTS FBO_DESC;
DROP TABLE IF EXISTS FBO_DONBR;
DROP TABLE IF EXISTS FBO_FOJA;
DROP TABLE IF EXISTS FBO_LINENBR;
DROP TABLE IF EXISTS FBO_LOCATION;
DROP TABLE IF EXISTS FBO_MODNBR;
DROP TABLE IF EXISTS FBO_NAICS;
DROP TABLE IF EXISTS FBO_NTYPE;
DROP TABLE IF EXISTS FBO_OFFADD;
DROP TABLE IF EXISTS FBO_OFFICE;
DROP TABLE IF EXISTS FBO_PASSWORD;
DROP TABLE IF EXISTS FBO_POPADDRESS;
DROP TABLE IF EXISTS FBO_POPCOUNTRY;
DROP TABLE IF EXISTS FBO_POPZIP;
DROP TABLE IF EXISTS FBO_RESPDATE;
DROP TABLE IF EXISTS FBO_SETASIDE;
DROP TABLE IF EXISTS FBO_SOLNBR;
DROP TABLE IF EXISTS FBO_STAUTH;
DROP TABLE IF EXISTS FBO_SUBJECT;
DROP TABLE IF EXISTS FBO_URL;
DROP TABLE IF EXISTS FBO_ZIP;
DROP TABLE IF EXISTS FBO_POC_EMAIL;
DROP TABLE IF EXISTS FBO_POC_EMAIL_DESC;
DROP TABLE IF EXISTS FBO_LINK_URL;
DROP TABLE IF EXISTS FBO_LINK_DESC;

CREATE TABLE FBO_ARCHDATE (
	ID BIGSERIAL,
	VALUE DATE
);

CREATE TABLE FBO_AWARDEE (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_AWDAMT (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_AWDDATE (
	ID BIGSERIAL,
	VALUE DATE
);

CREATE TABLE FBO_AWDNBR (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_CBAC (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_CLASSCOD (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_CONTACT (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_CORRECTION (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_DATE (
	ID BIGSERIAL,
	VALUE DATE
);

CREATE TABLE FBO_DESC (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_DONBR (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_FOJA (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_LINENBR (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_LOCATION (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_MODNBR (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_NAICS (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_NTYPE (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_OFFADD (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_OFFICE (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_PASSWORD (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_POPADDRESS (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_POPCOUNTRY (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_POPZIP (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_RESPDATE (
	ID BIGSERIAL,
	VALUE DATE
);

CREATE TABLE FBO_SETASIDE (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_SOLNBR (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_STAUTH (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_SUBJECT (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_URL (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_ZIP (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_POC_EMAIL (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_POC_EMAIL_DESC (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_LINK_URL (
	ID BIGSERIAL,
	VALUE TEXT
);

CREATE TABLE FBO_LINK_DESC (
	ID BIGSERIAL,
	VALUE TEXT
);


INSERT INTO FBO_ARCHDATE (VALUE) SELECT DISTINCT FBO_ARCHDATE FROM NOTICES;
INSERT INTO FBO_AWARDEE (VALUE) SELECT DISTINCT FBO_AWARDEE FROM NOTICES;
INSERT INTO FBO_AWDAMT (VALUE) SELECT DISTINCT FBO_AWDAMT FROM NOTICES;
INSERT INTO FBO_AWDDATE (VALUE) SELECT DISTINCT FBO_AWDDATE FROM NOTICES;
INSERT INTO FBO_AWDNBR (VALUE) SELECT DISTINCT FBO_AWDNBR FROM NOTICES;
INSERT INTO FBO_CBAC (VALUE) SELECT DISTINCT FBO_CBAC FROM NOTICES;
INSERT INTO FBO_CLASSCOD (VALUE) SELECT DISTINCT FBO_CLASSCOD FROM NOTICES;
INSERT INTO FBO_CONTACT (VALUE) SELECT DISTINCT FBO_CONTACT FROM NOTICES;
INSERT INTO FBO_CORRECTION (VALUE) SELECT DISTINCT FBO_CORRECTION FROM NOTICES;
INSERT INTO FBO_DATE (VALUE) SELECT DISTINCT FBO_DATE FROM NOTICES;
INSERT INTO FBO_DESC (VALUE) SELECT DISTINCT FBO_DESC FROM NOTICES;
INSERT INTO FBO_DONBR (VALUE) SELECT DISTINCT FBO_DONBR FROM NOTICES;
INSERT INTO FBO_FOJA (VALUE) SELECT DISTINCT FBO_FOJA FROM NOTICES;
INSERT INTO FBO_LINENBR (VALUE) SELECT DISTINCT FBO_LINENBR FROM NOTICES;
INSERT INTO FBO_LOCATION (VALUE) SELECT DISTINCT FBO_LOCATION FROM NOTICES;
INSERT INTO FBO_MODNBR (VALUE) SELECT DISTINCT FBO_MODNBR FROM NOTICES;
INSERT INTO FBO_NAICS (VALUE) SELECT DISTINCT FBO_NAICS FROM NOTICES;
INSERT INTO FBO_NTYPE (VALUE) SELECT DISTINCT FBO_NTYPE FROM NOTICES;
INSERT INTO FBO_OFFADD (VALUE) SELECT DISTINCT FBO_OFFADD FROM NOTICES;
INSERT INTO FBO_OFFICE (VALUE) SELECT DISTINCT FBO_OFFICE FROM NOTICES;
INSERT INTO FBO_PASSWORD (VALUE) SELECT DISTINCT FBO_PASSWORD FROM NOTICES;
INSERT INTO FBO_POPADDRESS (VALUE) SELECT DISTINCT FBO_POPADDRESS FROM NOTICES;
INSERT INTO FBO_POPCOUNTRY (VALUE) SELECT DISTINCT FBO_POPCOUNTRY FROM NOTICES;
INSERT INTO FBO_POPZIP (VALUE) SELECT DISTINCT FBO_POPZIP FROM NOTICES;
INSERT INTO FBO_RESPDATE (VALUE) SELECT DISTINCT FBO_RESPDATE FROM NOTICES;
INSERT INTO FBO_SETASIDE (VALUE) SELECT DISTINCT FBO_SETASIDE FROM NOTICES;
INSERT INTO FBO_SOLNBR (VALUE) SELECT DISTINCT FBO_SOLNBR FROM NOTICES;
INSERT INTO FBO_STAUTH (VALUE) SELECT DISTINCT FBO_STAUTH FROM NOTICES;
INSERT INTO FBO_SUBJECT (VALUE) SELECT DISTINCT FBO_SUBJECT FROM NOTICES;
INSERT INTO FBO_URL (VALUE) SELECT DISTINCT FBO_URL FROM NOTICES;
INSERT INTO FBO_ZIP (VALUE) SELECT DISTINCT FBO_ZIP FROM NOTICES;
INSERT INTO FBO_POC_EMAIL (VALUE) SELECT DISTINCT FBO_POC_EMAIL FROM NOTICES;
INSERT INTO FBO_POC_EMAIL_DESC (VALUE) SELECT DISTINCT FBO_POC_EMAIL_DESC FROM NOTICES;
INSERT INTO FBO_LINK_URL (VALUE) SELECT DISTINCT FBO_LINK_URL FROM NOTICES;
INSERT INTO FBO_LINK_DESC (VALUE) SELECT DISTINCT FBO_LINK_DESC FROM NOTICES;

COMMIT; 