BEGIN;

\set PWD '\'' `echo $PWD`
\set CSVDIR :PWD '/parsed/csv'
\set GENERIC_CSVDIR :PWD '/generic/csv'

\set AMDCSS_CSV :CSVDIR '/fbofeed_AMDCSS.csv\''
\set ARCHIVE_CSV :CSVDIR '/fbofeed_ARCHIVE.csv\''
\set AWARD_CSV :CSVDIR '/fbofeed_AWARD.csv\''
\set COMBINE_CSV :CSVDIR '/fbofeed_COMBINE.csv\''
\set FAIROPP_CSV :CSVDIR '/fbofeed_FAIROPP.csv\''
\set JA_CSV :CSVDIR '/fbofeed_JA.csv\''
\set MOD_CSV :CSVDIR '/fbofeed_MOD.csv\''
\set PRESOL_CSV :CSVDIR '/fbofeed_PRESOL.csv\''
\set SNOTE_CSV :CSVDIR '/fbofeed_SNOTE.csv\''
\set SRCSGT_CSV :CSVDIR '/fbofeed_SRCSGT.csv\''
\set UNARCHIVE_CSV :CSVDIR '/fbofeed_UNARCHIVE.csv\''
\set FSTD_CSV :CSVDIR '/fbofeed_FSTD.csv\''
\set SSALE_CSV :CSVDIR '/fbofeed_SSALE.csv\''
\set ITB_CSV :CSVDIR '/fbofeed_ITB.csv\''

\set NOTICE_COLS 'AGENCY, OLD_ARCHDATE, AWARDEE, AWDAMT, OLD_AWDDATE, AWDNBR, CBAC, CLASSCOD, CONTACT, CORRECTION, OLD_DATE, NOTICE_DESC, DONBR, FOJA, LINENBR, LOCATION, MODNBR, NAICS, NTYPE, OFFADD, OFFICE, PASSWORD, POPADDRESS, POPCOUNTRY, POPZIP, OLD_RESPDATE, SETASIDE, SOLNBR, STAUTH, SUBJECT, URL, OLD_YEAR, ZIP, POC_EMAIL, POC_EMAIL_DESC, LINK_URL, LINK_DESC, NOTICE_TYPE'
\set INSERT_COLS 'AGENCY, ARCHDATE AS OLD_ARCHDATE, AWARDEE, AWDAMT, AWDDATE AS OLD_AWDDATE, AWDNBR, CBAC, CLASSCOD, CONTACT, CORRECTION, NOTICE_DATE AS OLD_DATE, NOTICE_DESC, DONBR, FOJA, LINENBR, LOCATION, MODNBR, NAICS, NTYPE, OFFADD, OFFICE, PASSWORD, POPADDRESS, POPCOUNTRY, POPZIP, RESPDATE AS OLD_RESPDATE, SETASIDE, SOLNBR, STAUTH, SUBJECT, URL, YEAR AS OLD_YEAR, ZIP, POC_EMAIL, POC_EMAIL_DESC, LINK_URL, LINK_DESC'

\set SETASIDE_TYPES_FILENAME :GENERIC_CSVDIR '/setaside_types.csv\''
\set PRODUCT_CODES_FILENAME :GENERIC_CSVDIR '/product_codes.csv\''
\set SERVICE_CODES_FILENAME :GENERIC_CSVDIR '/service_codes.csv\''
\set NAICS_CODES_FILENAME :GENERIC_CSVDIR '/naics.csv\''
\set JA_STAT_AUTH_FILENAME :GENERIC_CSVDIR '/ja_stat_auth.csv\''
\set FAIROPPS_JUST_AUTH_FILENAME :GENERIC_CSVDIR '/fairopp_just_auth.csv\''

DROP TABLE IF EXISTS AMDCSS;
DROP TABLE IF EXISTS ARCHIVE;
DROP TABLE IF EXISTS AWARD;
DROP TABLE IF EXISTS COMBINE;
DROP TABLE IF EXISTS FAIROPP;
DROP TABLE IF EXISTS FBO_RECORD;
DROP TABLE IF EXISTS FSTD;
DROP TABLE IF EXISTS JA;
DROP TABLE IF EXISTS MOD;
DROP TABLE IF EXISTS PRESOL;
DROP TABLE IF EXISTS SNOTE;
DROP TABLE IF EXISTS SRCSGT;
DROP TABLE IF EXISTS UNARCHIVE;
DROP TABLE IF EXISTS ITB;
DROP TABLE IF EXISTS SSALE;
DROP TABLE IF EXISTS NOTICES;
DROP TABLE IF EXISTS SETASIDE_TYPES;
DROP TABLE IF EXISTS PRODUCT_CODES;
DROP TABLE IF EXISTS SERVICE_CODES;
DROP TABLE IF EXISTS NAICS_CODES;
DROP TABLE IF EXISTS FAIROPPS_JUST_AUTH;
DROP TABLE IF EXISTS JA_STAT_AUTH;

CREATE TABLE SETASIDE_TYPES (
	TYPE TEXT,
	FAR_REFERENCE TEXT
);

CREATE TABLE PRODUCT_CODES (
	CODE TEXT,
	DESCRIPTION TEXT
);

CREATE TABLE SERVICE_CODES (
	CODE TEXT,
	DESCRIPTION TEXT
);

CREATE TABLE NAICS_CODES (
	CODE TEXT,
	DESCRIPTION TEXT
);

CREATE TABLE JA_STAT_AUTH (
	DESCRIPTION TEXT
);

CREATE TABLE FAIROPPS_JUST_AUTH (
	DESCRIPTION TEXT
);

COPY SETASIDE_TYPES FROM :SETASIDE_TYPES_FILENAME WITH CSV;
COPY PRODUCT_CODES FROM :PRODUCT_CODES_FILENAME WITH CSV;
COPY SERVICE_CODES FROM :SERVICE_CODES_FILENAME WITH CSV;
COPY NAICS_CODES FROM :NAICS_CODES_FILENAME WITH CSV;
COPY FAIROPPS_JUST_AUTH FROM :FAIROPPS_JUST_AUTH_FILENAME WITH CSV;
COPY JA_STAT_AUTH FROM :JA_STAT_AUTH_FILENAME WITH CSV;

CREATE INDEX ON SETASIDE_TYPES (TYPE, FAR_REFERENCE);
CREATE INDEX ON PRODUCT_CODES (CODE, DESCRIPTION);
CREATE INDEX ON SERVICE_CODES (CODE, DESCRIPTION);
CREATE INDEX ON NAICS_CODES (CODE, DESCRIPTION);
CREATE INDEX ON JA_STAT_AUTH (DESCRIPTION);
CREATE INDEX ON FAIROPPS_JUST_AUTH (DESCRIPTION);

CREATE TEMPORARY TABLE FBO_RECORD (
AGENCY TEXT,
ARCHDATE TEXT,
AWARDEE TEXT,
AWDAMT TEXT,
AWDDATE TEXT,
AWDNBR TEXT,
CBAC TEXT,
CLASSCOD TEXT,
CONTACT TEXT,
CORRECTION TEXT,
NOTICE_DATE TEXT,
NOTICE_DESC TEXT,
DONBR TEXT,
EMAIL TEXT,
FOJA TEXT,
LINENBR TEXT,
LINK TEXT,
LOCATION TEXT,
MODNBR TEXT,
NAICS TEXT,
NTYPE TEXT,
OFFADD TEXT,
OFFICE TEXT,
PASSWORD TEXT,
POPADDRESS TEXT,
POPCOUNTRY TEXT,
POPZIP TEXT,
RESPDATE TEXT,
SETASIDE TEXT,
SOLNBR TEXT,
STAUTH TEXT,
SUBJECT TEXT,
URL TEXT,
YEAR TEXT,
ZIP TEXT,
POC_EMAIL TEXT,
POC_EMAIL_DESC TEXT,
LINK_URL TEXT,
LINK_DESC TEXT,
FILENAME TEXT
);

CREATE UNLOGGED TABLE NOTICES (
ID BIGSERIAL,
NOTICE_TYPE TEXT NOT NULL,
AGENCY TEXT,
OLD_ARCHDATE TEXT,
ARCHDATE DATE,
AWARDEE TEXT,
AWDAMT TEXT,
OLD_AWDDATE TEXT,
AWDDATE DATE,
AWDNBR TEXT,
CBAC TEXT,
CLASSCOD TEXT,
CONTACT TEXT,
CORRECTION TEXT,
OLD_DATE TEXT,
NOTICE_DATE DATE,
NOTICE_DESC TEXT,
DONBR TEXT,
FOJA TEXT,
LINENBR TEXT,
LOCATION TEXT,
MODNBR TEXT,
NAICS TEXT,
NTYPE TEXT,
OFFADD TEXT,
OFFICE TEXT,
PASSWORD TEXT,
POPADDRESS TEXT,
POPCOUNTRY TEXT,
POPZIP TEXT,
OLD_RESPDATE TEXT,
RESPDATE DATE,
SETASIDE TEXT,
SOLNBR TEXT,
STAUTH TEXT,
SUBJECT TEXT,
OLD_YEAR TEXT,
URL TEXT,
ZIP TEXT,
POC_EMAIL TEXT,
POC_EMAIL_DESC TEXT,
LINK_URL TEXT,
LINK_DESC TEXT
);

CREATE TEMPORARY TABLE PRESOL (LIKE FBO_RECORD);
CREATE TEMPORARY TABLE AMDCSS (LIKE FBO_RECORD);
CREATE TEMPORARY TABLE ARCHIVE (LIKE FBO_RECORD);
CREATE TEMPORARY TABLE AWARD (LIKE FBO_RECORD);
CREATE TEMPORARY TABLE COMBINE (LIKE FBO_RECORD);
CREATE TEMPORARY TABLE FAIROPP (LIKE FBO_RECORD);
CREATE TEMPORARY TABLE FSTD (LIKE FBO_RECORD);
CREATE TEMPORARY TABLE ITB (LIKE FBO_RECORD);
CREATE TEMPORARY TABLE JA	 (LIKE FBO_RECORD);
CREATE TEMPORARY TABLE MOD (LIKE FBO_RECORD);
CREATE TEMPORARY TABLE SNOTE (LIKE FBO_RECORD);
CREATE TEMPORARY TABLE SRCSGT (LIKE FBO_RECORD);
CREATE TEMPORARY TABLE SSALE (LIKE FBO_RECORD);
CREATE TEMPORARY TABLE UNARCHIVE (LIKE FBO_RECORD);

COPY AMDCSS		FROM :AMDCSS_CSV WITH CSV;
COPY ARCHIVE	FROM :ARCHIVE_CSV WITH CSV;
COPY AWARD		FROM :AWARD_CSV WITH CSV;
COPY COMBINE	FROM :COMBINE_CSV WITH CSV;
COPY FAIROPP	FROM :FAIROPP_CSV WITH CSV;
COPY FSTD		FROM :FSTD_CSV WITH CSV;
COPY ITB		FROM :ITB_CSV WITH CSV;
COPY JA			FROM :JA_CSV WITH CSV;
COPY MOD		FROM :MOD_CSV WITH CSV;
COPY PRESOL		FROM :PRESOL_CSV WITH CSV;
COPY SNOTE		FROM :SNOTE_CSV WITH CSV;
COPY SRCSGT		FROM :SRCSGT_CSV WITH CSV;
COPY SSALE		FROM :SSALE_CSV WITH CSV;
COPY UNARCHIVE	FROM :UNARCHIVE_CSV WITH CSV;

INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'AMDCSS' AS NOTICE_TYPE FROM AMDCSS;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'ARCHIVE' AS NOTICE_TYPE FROM ARCHIVE;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'AWARD' AS NOTICE_TYPE FROM AWARD;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'COMBINE' AS NOTICE_TYPE FROM COMBINE;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'FAIROPP' AS NOTICE_TYPE FROM FAIROPP;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'FSTD' AS NOTICE_TYPE FROM FSTD;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'ITB' AS NOTICE_TYPE FROM ITB;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'JA' AS NOTICE_TYPE FROM JA;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'MOD' AS NOTICE_TYPE FROM MOD;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'PRESOL' AS NOTICE_TYPE FROM PRESOL;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'SNOTE' AS NOTICE_TYPE FROM SNOTE;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'SRCSGT' AS NOTICE_TYPE FROM SRCSGT;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'SSALE' AS NOTICE_TYPE FROM SSALE;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'UNARCHIVE' AS NOTICE_TYPE FROM UNARCHIVE;

UPDATE NOTICES SET NOTICE_DATE = to_date(OLD_DATE||OLD_YEAR, 'MMDDYY');
UPDATE NOTICES SET AWDDATE = to_date(OLD_AWDDATE, 'YYYY-MM-DD') WHERE OLD_AWDDATE ~ '00:00:00';
UPDATE NOTICES SET AWDDATE = to_date(OLD_AWDDATE, 'MMDDYY') WHERE OLD_AWDDATE ~ '[0-9]{6}';
UPDATE NOTICES SET RESPDATE = to_date(OLD_RESPDATE, 'MMDDYY');
UPDATE NOTICES SET ARCHDATE = to_date(OLD_ARCHDATE, 'MMDDYYYY');

ALTER TABLE NOTICES DROP COLUMN OLD_DATE;
ALTER TABLE NOTICES DROP COLUMN OLD_ARCHDATE;
ALTER TABLE NOTICES DROP COLUMN OLD_RESPDATE;
ALTER TABLE NOTICES DROP COLUMN OLD_YEAR;

CREATE INDEX ON NOTICES (NOTICE_TYPE, 

COMMIT;

