BEGIN;

\set PWD '\'' `echo $PWD`
\set NOTICE_COLS 'AGENCY, OLD_ARCHDATE, AWARDEE, AWDAMT, OLD_AWDDATE, AWDNBR, CBAC, CLASSCOD, CONTACT, CORRECTION, OLD_DATE, NOTICE_DESC, DONBR, FOJA, LINENBR, LOCATION, MODNBR, NAICS, NTYPE, OFFADD, OFFICE, PASSWORD, POPADDRESS, POPCOUNTRY, POPZIP, OLD_RESPDATE, SETASIDE, SOLNBR, STAUTH, SUBJECT, URL, OLD_YEAR, ZIP, POC_EMAIL, POC_EMAIL_DESC, LINK_URL, LINK_DESC, NOTICE_TYPE'
\set INSERT_COLS 'AGENCY, ARCHDATE AS OLD_ARCHDATE, AWARDEE, AWDAMT, AWDDATE AS OLD_AWDDATE, AWDNBR, CBAC, CLASSCOD, CONTACT, CORRECTION, NOTICE_DATE AS OLD_DATE, NOTICE_DESC, DONBR, FOJA, LINENBR, LOCATION, MODNBR, NAICS, NTYPE, OFFADD, OFFICE, PASSWORD, POPADDRESS, POPCOUNTRY, POPZIP, RESPDATE AS OLD_RESPDATE, SETASIDE, SOLNBR, STAUTH, SUBJECT, URL, YEAR AS OLD_YEAR, ZIP, POC_EMAIL, POC_EMAIL_DESC, LINK_URL, LINK_DESC'

DROP TABLE IF EXISTS NOTICES;

CREATE UNLOGGED TABLE NOTICES (
ID BIGSERIAL,
NOTICE_TYPE TEXT NOT NULL,
AGENCY TEXT,
OLD_ARCHDATE TEXT,
ARCHDATE DATE,
AWARDEE TEXT,
AWDAMT TEXT,
OLD_AWDDATE TEXT,
AWDDATE DATE,
AWDNBR TEXT,
CBAC TEXT,
CLASSCOD TEXT,
CONTACT TEXT,
CORRECTION TEXT,
OLD_DATE TEXT,
NOTICE_DATE DATE,
NOTICE_DESC TEXT,
DONBR TEXT,
FOJA TEXT,
LINENBR TEXT,
LOCATION TEXT,
MODNBR TEXT,
NAICS TEXT,
NTYPE TEXT,
OFFADD TEXT,
OFFICE TEXT,
PASSWORD TEXT,
POPADDRESS TEXT,
POPCOUNTRY TEXT,
POPZIP TEXT,
OLD_RESPDATE TEXT,
RESPDATE DATE,
SETASIDE TEXT,
SOLNBR TEXT,
STAUTH TEXT,
SUBJECT TEXT,
OLD_YEAR TEXT,
URL TEXT,
ZIP TEXT,
POC_EMAIL TEXT,
POC_EMAIL_DESC TEXT,
LINK_URL TEXT,
LINK_DESC TEXT
);

INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'AMDCSS' AS NOTICE_TYPE FROM AMDCSS;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'ARCHIVE' AS NOTICE_TYPE FROM ARCHIVE;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'AWARD' AS NOTICE_TYPE FROM AWARD;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'COMBINE' AS NOTICE_TYPE FROM COMBINE;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'FAIROPP' AS NOTICE_TYPE FROM FAIROPP;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'FSTD' AS NOTICE_TYPE FROM FSTD;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'ITB' AS NOTICE_TYPE FROM ITB;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'JA' AS NOTICE_TYPE FROM JA;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'MOD' AS NOTICE_TYPE FROM MOD;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'PRESOL' AS NOTICE_TYPE FROM PRESOL;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'SNOTE' AS NOTICE_TYPE FROM SNOTE;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'SRCSGT' AS NOTICE_TYPE FROM SRCSGT;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'SSALE' AS NOTICE_TYPE FROM SSALE;
INSERT INTO NOTICES (:NOTICE_COLS) SELECT :INSERT_COLS, 'UNARCHIVE' AS NOTICE_TYPE FROM UNARCHIVE;

UPDATE NOTICES SET NOTICE_DATE = to_date(OLD_DATE||OLD_YEAR, 'MMDDYY');
UPDATE NOTICES SET AWDDATE = to_date(OLD_AWDDATE, 'YYYY-MM-DD') WHERE OLD_AWDDATE ~ '00:00:00';
UPDATE NOTICES SET AWDDATE = to_date(OLD_AWDDATE, 'MMDDYY') WHERE OLD_AWDDATE ~ '[0-9]{6}';
UPDATE NOTICES SET RESPDATE = to_date(OLD_RESPDATE, 'MMDDYY');
UPDATE NOTICES SET ARCHDATE = to_date(OLD_ARCHDATE, 'MMDDYYYY');

ALTER TABLE NOTICES DROP COLUMN OLD_DATE;
ALTER TABLE NOTICES DROP COLUMN OLD_ARCHDATE;
ALTER TABLE NOTICES DROP COLUMN OLD_RESPDATE;
ALTER TABLE NOTICES DROP COLUMN OLD_YEAR;

COMMIT;

