BEGIN;

UPDATE NOTICES SET NOTICE_DATE = to_date(OLD_DATE||OLD_YEAR, 'MMDDYY');
UPDATE NOTICES SET AWDDATE = to_date(OLD_AWDDATE, 'YYYY-MM-DD') WHERE OLD_AWDDATE ~ '00:00:00';
UPDATE NOTICES SET AWDDATE = to_date(OLD_AWDDATE, 'MMDDYY') WHERE OLD_AWDDATE ~ '[0-9]{6}';
UPDATE NOTICES SET RESPDATE = to_date(OLD_RESPDATE, 'MMDDYY') WHERE OLD_RESPDATE ~ '[0-9]{6}';
UPDATE NOTICES SET ARCHDATE = to_date(OLD_ARCHDATE, 'MMDDYYYY') WHERE OLD_ARCHDATE ~ '[0-9]{8}';

ALTER TABLE NOTICES DROP COLUMN OLD_DATE;
ALTER TABLE NOTICES DROP COLUMN OLD_ARCHDATE;
ALTER TABLE NOTICES DROP COLUMN OLD_RESPDATE;
ALTER TABLE NOTICES DROP COLUMN OLD_YEAR;

COMMIT;
